language: bash
dist: xenial
virt: lxt
os: linux
arch: amd64

before_script:
  - wget -c https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64
  - sudo install -Dm0755 -t /usr/local/bin shfmt_v3.5.1_linux_amd64
  - wget -c https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.aarch64.tar.xz
  - tar -xJf shellcheck-v0.8.0.linux.aarch64.tar.xz shellcheck-v0.8.0/shellcheck
  - sudo install -Dm0755 -t /usr/local/bin shellcheck-v0.8.0/shellcheckø
  - export PATH="${PATH}:/usr/local/bin"

addons:
  apt:
    packages:
      - shunit2
      - shellcheck
      - gnupg2

script:
  - make test
