language: bash
dist: focal
virt: vm
os: linux
arch: amd64

install:
  - wget -c https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64
  - sudo install -Dm0755 shfmt_v3.5.1_linux_amd64 /usr/local/bin/shfmt
  - wget -c https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz
  - tar -xJf shellcheck-v0.8.0.linux.x86_64.tar.xz shellcheck-v0.8.0/shellcheck
  - sudo install -Dm0755 -t /usr/local/bin shellcheck-v0.8.0/shellcheck

before_script:
  - export PATH="${PATH}:/usr/local/bin"

addons:
  apt:
    packages:
      - shunit2
      - gnupg2
      - pass

script:
  - make test
